pool:
  name: Azure Pipelines
  demands: npm
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - master

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'run lint'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run lint'

- task: Npm@1
  displayName: 'run test'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: 'Publish Test Results junit.xml'
  inputs:
    testResultsFiles: junit.xml

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage/cobertura-coverage.xml'

- task: Npm@1
  displayName: 'run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
