export enum ActivityType {
  INVITATION = 0,
  EVENT_UPDATED = 1,
  NEW_COMMENT = 2,
  COMMENT_RESPONDED = 3,
  NEW_FOLLOWER = 4,
  FRIEND_REQUEST = 5,
  FRIEND_REQUEST_ACCEPTED = 6,
  NEW_EVENT_PARTICIPANT = 7,
}
