version: '3'

services:
    activate-postgres:
        container_name: activate-postgres
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - ./db-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=activate
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5


